package pipeline

import "github.com/Keyhole-Koro/SynthifyShared/domain"

type PipelineContext struct {
	JobID       string
	JobType     string
	DocumentID  string
	WorkspaceID string
	TreeID      string
	Capability  *domain.JobCapability

	FileURI  string
	Filename string
	MimeType string

	SourceFiles []SourceFile

	RawText string

	Chunks  []Chunk
	Outline []string

	DocumentBrief *DocumentBrief
	SectionBriefs []SectionBrief

	SynthesizedItems []SynthesizedItem

	ItemIDMap map[string]string

	// StageInstructions holds custom instructions for each stage,
	// typically generated by the LLM during the planning phase.
	StageInstructions map[string]string
}

type SourceFile struct {
	Filename string
	URI      string
	MimeType string
	Content  []byte
}

type Chunk struct {
	ChunkIndex int
	Heading    string
	Text       string
}

type DocumentBrief struct {
	Topic        string
	Level01Hints []string
	ClaimSummary string
	Entities     []string
	Outline      []string
}

type SectionBrief struct {
	Heading         string
	Topic           string
	ItemCandidates  []string
	ConnectionHints string
}

type SynthesizedItem struct {
	LocalID        string
	Label          string
	Level          int
	Description    string
	SummaryHTML    string
	ParentLocalID  string
	ChildLocalIDs  []string
	SourceChunkIDs []string
}
