package pipeline

import "github.com/Keyhole-Koro/SynthifyShared/domain"

type PipelineContext struct {
	JobID       string
	JobType     string
	DocumentID  string
	WorkspaceID string
	TreeID      string
	Capability  *domain.JobCapability

	FileURI  string
	Filename string
	MimeType string

	SourceFiles []domain.SourceFile

	RawText string

	Chunks  []domain.Chunk
	Outline []string

	DocumentBrief *domain.DocumentBrief
	SectionBriefs []domain.SectionBrief

	SynthesizedItems []domain.SynthesizedItem

	ItemIDMap map[string]string

	// StageInstructions holds custom instructions for each stage,
	// typically generated by the LLM during the planning phase.
	StageInstructions map[string]string
}
